os: linux
dist: xenial
language: generic

services:
  - docker

install: skip

stages:
  - name: Docker Build
  - name: Docker Manifest
    if: branch = master && type = push

jobs:
  include:
    - stage: Docker Build
      arch: amd64
      script:
        - docker build -t dullage/gunicorn-python:3.8-amd64 ./3.8
      deploy:
        provider: script
        script: bash ./.travis/deploy-builds.sh 3.8-amd64
        on:
          branch: master
    - arch: amd64
      script:
        - docker build -t dullage/gunicorn-python:3.8-alpine-amd64 ./3.8-alpine
      deploy:
        provider: script
        script: bash ./.travis/deploy-builds.sh 3.8-alpine-amd64
        on:
          branch: master
    - arch: arm64
      script:
        - docker build -t dullage/gunicorn-python:3.8-arm64 ./3.8
      deploy:
        provider: script
        script: bash ./.travis/deploy-builds.sh 3.8-arm64
        on:
          branch: master
    - arch: arm64
      script:
        - docker build -t dullage/gunicorn-python:3.8-alpine-arm64 ./3.8-alpine
      deploy:
        provider: script
        script: bash ./.travis/deploy-builds.sh 3.8-alpine-arm64
        on:
          branch: master

    - stage: Docker Manifest
      arch: amd64
      script:
        - export DOCKER_CLI_EXPERIMENTAL="enabled"
        - docker manifest create dullage/gunicorn-python:3.8 dullage/gunicorn-python:3.8-amd64 dullage/gunicorn-python:3.8-arm64
        - docker manifest create dullage/gunicorn-python:3.8-alpine dullage/gunicorn-python:3.8-alpine-amd64 dullage/gunicorn-python:3.8-alpine-arm64
        - docker manifest create dullage/gunicorn-python:latest dullage/gunicorn-python:3.8-alpine-amd64 dullage/gunicorn-python:3.8-alpine-arm64
      deploy:
        provider: script
        script: bash ./.travis/deploy-manifest.sh
        on:
          branch: master
